import { Link } from 'react-router-dom';
import type { ReactNode } from 'react';
import { ArrowUpRight, CheckCircle2, ShieldCheck, Sparkles } from 'lucide-react';
import styles from './LandingPage.module.css';
import s from '../styles/shared.module.css';
import { BLOG_POSTS } from './blog/blogData';
import { HOME_FAQ } from '../lib/faq';
import { WORKSHOPS_PATH } from '../lib/seo';
import { useCountUp, useRevealRoot } from '../lib/motion';

type ProofProject = {
  name: string;
  type: string;
  description: string;
  stack: string;
  href?: string;
  image?: string;
  imageAlt?: string;
  portraitImage?: boolean;
  painPoint?: string;
  status: 'Live' | 'Testing';
  featured?: boolean;
};

const proof: ProofProject[] = [
  {
    name: "Hunter's Holistic Health",
    type: 'Healthcare education platform',
    description: 'A live functional medicine education platform with privacy-first tools, daily tracking, and a structured member experience.',
    stack: 'React · Supabase · n8n · Vercel',
    href: 'https://www.huntersholistichealth.com',
    image: '/proof/hhh-command-center.webp',
    imageAlt: "Hunter's Holistic Health Daily Command Center product screen",
    status: 'Live',
    featured: true,
  },
  {
    name: 'Consistency Automation',
    type: 'Member experience automation',
    description: 'A scheduled system delivers fasting-window reminders, supplement prompts, and an energy check-in across the member app and Telegram. This personal demonstration keeps the bot name private.',
    painPoint: 'When reminders and check-ins rely on manual outreach, consistency becomes difficult to sustain.',
    stack: 'n8n · Telegram · Push notifications',
    image: '/proof/hhh-reminders-energy-checkin-proof.webp',
    imageAlt: 'Side-by-side view of reminder settings and an automated Telegram energy check-in, with the bot name hidden',
    status: 'Live',
    featured: true,
  },
  {
    name: 'Pharmacy Decoder',
    type: 'Pharmacy education product',
    description: '340+ scenario-based pharmacy law questions with school access, OTP verification, and progress tracking.',
    stack: 'JavaScript · Apps Script · Airtable',
    href: 'https://pharmacydecoder.com',
    image: '/proof/pharmacy-decoder.webp',
    imageAlt: 'Pharmacy Decoder product logo',
    status: 'Live',
  },
  {
    name: 'DeIDGuard',
    type: 'Privacy browser extension',
    description: 'A browser extension built to detect and mask identifiers before text enters an AI workflow.',
    stack: 'Chrome Extension API · JavaScript',
    image: '/proof/deidguard.svg',
    imageAlt: 'DeIDGuard privacy extension graphic',
    status: 'Testing',
  },
  {
    name: 'AI Morning Brief',
    type: 'Operational AI automation',
    description: 'A scheduled AI brief turns non-clinical operational signals into a concise review point. The public preview intentionally hides message contents.',
    stack: 'n8n · Gmail · Telegram · Calendar',
    image: '/proof/oracle-n8n-morning-brief-redacted.webp',
    imageAlt: 'Redacted mobile daily brief generated by an AI automation',
    portraitImage: true,
    status: 'Live',
  },
  {
    name: 'Email-to-Brief Automation',
    type: 'Automation workflow',
    description: 'A scheduled workflow moves approved operational signals through summarization, task extraction, and calendar routing. Account sources are redacted in the public view.',
    stack: 'n8n · AI summarization · Telegram · Calendar',
    image: '/proof/oracle-n8n-email-brief-workflow-redacted.webp',
    imageAlt: 'Redacted n8n workflow for an automated email-to-brief system',
    status: 'Live',
  },
  {
    name: 'Non-PHI Intake Router',
    type: 'Workflow architecture',
    description: 'A routing layer organizes early-access, support, and feature-request messages before a team acts. Clinical handling is excluded from this public preview.',
    stack: 'n8n · Google Sheets · Email',
    image: '/proof/n8n-intake-router-redacted.webp',
    imageAlt: 'Redacted n8n intake router showing non-clinical workflow branches',
    status: 'Live',
  },
  {
    name: 'CCA-F Exam Prep',
    type: 'Claude Code certification prep',
    description: '207 practice questions sourced from official Anthropic documentation, built for deliberate exam practice.',
    stack: 'React · TypeScript · Stripe',
    href: '/exam-prep',
    status: 'Live',
  },
];

const process = [
  ['01', 'Start with the real workflow', 'Map the decisions, risks, and repetitive work before choosing a model or automation tool.'],
  ['02', 'Separate sensitive data', 'Design the non-PHI and covered lanes first. The privacy boundary is architecture, not a disclaimer.'],
  ['03', 'Build a working version', 'Use Claude Code, n8n, Supabase, Apps Script, and the smallest stack that can do the job reliably.'],
  ['04', 'Test what can fail', 'Check permissions, edge cases, mobile behavior, accessibility, and the handoff before calling it shipped.'],
];

const teaching = [
  ['For healthcare professionals', 'Build useful AI tools without exposing sensitive data', 'Learn to identify safe use cases, draw the data boundary, and turn a repetitive workflow into a working system.'],
  ['For organizations', 'Move your team from AI curiosity to responsible practice', 'Hands-on workshops connect AI literacy to the policies, workflows, and decisions your staff already manages.'],
  ['For builders', 'Use AI coding tools with stronger judgment', 'Learn how to direct Claude Code, structure context, inspect output, and ship software you can explain.'],
];

// Animated stat. The number is rendered at its real value on the server and with
// reduced motion, so nothing depends on the animation running.
function Stat({ value, suffix, label }: { value: number; suffix?: string; label: string }) {
  const { ref, value: shown } = useCountUp(value);
  return (
    <div>
      <strong ref={ref as React.RefObject<HTMLElement>}>{shown}{suffix}</strong>
      <span>{label}</span>
    </div>
  );
}

function ProjectLink({ href, children }: { href: string; children: ReactNode }) {
  return href.startsWith('/') ? (
    <Link to={href} className={styles.projectLink}>{children}</Link>
  ) : (
    <a href={href} target="_blank" rel="noopener noreferrer" className={styles.projectLink}>{children}</a>
  );
}

export default function LandingPage() {
  const featuredPosts = BLOG_POSTS.slice(0, 3);
  const root = useRevealRoot<HTMLDivElement>();

  return (
    <div className={styles.page} ref={root}>
      <section className={styles.hero}>
        <div className={`${s.wrapWide} ${styles.heroGrid}`}>
          <div className={styles.heroCopy}>
            <p className={styles.eyebrow}>I Can Teach You AI, with Dr. Shallanda Hunter</p>
            <h1 className={styles.heroTitle}>Healthcare AI taught by a <span>PharmD who ships.</span></h1>
            <p className={styles.heroLead}>I teach healthcare professionals to build practical, compliance-conscious AI systems because I build and test them every day. Workshops for hospitals and schools, one-on-one sessions, and custom workflow builds, all designed so AI never touches protected health information.</p>
            <div className={styles.heroActions}>
              <Link to={WORKSHOPS_PATH} className={`${s.btnGold} ${s.btnLg}`}>Book a team workshop <ArrowUpRight size={17} aria-hidden="true" /></Link>
              <a href="#proof" className={`${s.btnOutline} ${s.btnLg}`}>See what I built</a>
            </div>
            <div className={styles.heroTrust} aria-label="Professional credentials and focus">
              <span>Dr. Shallanda Hunter</span><span>PharmD</span><span>Functional Medicine Educator</span><span>AI Builder</span>
            </div>
          </div>

          <div className={styles.heroVisual} aria-label="Dr. Shallanda Hunter and her live AI build system">
            <div className={styles.portraitFrame}>
              <div className={styles.portraitHalo} aria-hidden="true" />
              <img src="/dr-hunter-expert-studio.webp" width="720" height="986" alt="Dr. Shallanda Hunter, PharmD" className={styles.portrait} />
              <div className={styles.portraitCaption}><span className={styles.liveDot} aria-hidden="true" /><span>Building in public</span></div>
            </div>
            <div className={styles.systemCard}>
              <div className={styles.systemHeader}><span>Current build system</span><span className={styles.systemStatus}>4 products</span></div>
              <div className={styles.systemFlow} aria-label="Workflow from healthcare problem to tested product">
                <span className={styles.flowNode}>Healthcare problem</span><span className={styles.flowLine} aria-hidden="true" />
                <span className={styles.flowNode}>AI-assisted build</span><span className={styles.flowLine} aria-hidden="true" />
                <span className={`${styles.flowNode} ${styles.flowNodeLive}`}>Tested product</span>
              </div>
              <p>Claude Code · n8n · React · Supabase · Apps Script</p>
            </div>
          </div>
        </div>
      </section>

      <section className={styles.authorityStrip} aria-label="Proof at a glance">
        <div className={`${s.wrapWide} ${styles.authorityGrid}`}>
          <Stat value={4} label="working AI products" />
          <Stat value={340} suffix="+" label="pharmacy scenarios shipped" />
          <Stat value={207} label="Claude Code practice questions" />
          <div><ShieldCheck aria-hidden="true" /><span>privacy-first architecture</span></div>
        </div>
      </section>

      <section className={styles.proofSection} id="proof">
        <div className={s.wrapWide}>
          <div className={styles.sectionIntro} data-reveal>
            <div><span className={s.kickerGold}>Proof, not promises</span><h2 className={styles.sectionTitle}>The work is already live.</h2></div>
            <p>I teach from systems I have designed, built, tested, and maintained. Open the products. Inspect the decisions.</p>
          </div>
          <div className={styles.proofGrid}>
            {proof.map(project => (
              <article key={project.name} className={`${styles.projectCard} ${project.featured ? styles.projectFeatured : ''}`} data-reveal>
                {project.image ? (
                  <div className={styles.projectMedia}><img src={project.image} alt={project.imageAlt ?? ''} loading={project.featured ? 'eager' : 'lazy'} fetchPriority={project.featured ? 'high' : 'auto'} decoding="async" width="1024" height="1024" className={project.portraitImage ? styles.projectMediaPortrait : undefined} /></div>
                ) : (
                  <div className={styles.examPreview} aria-hidden="true"><span>CCA-F · Practice mode</span><strong>What should the agent do next?</strong><i /><i /><i /></div>
                )}
                <div className={styles.projectContent}>
                  <div className={styles.projectMeta}><span>{project.type}</span><span className={project.status === 'Live' ? styles.statusLive : styles.statusTesting}><i aria-hidden="true" /> {project.status}</span></div>
                  {project.painPoint && <p className={styles.projectPainPoint}><span>Pain point</span>{project.painPoint}</p>}
                  <h3>{project.name}</h3><p>{project.description}</p><span className={styles.projectStack}>{project.stack}</span>
                  {project.href && <ProjectLink href={project.href}>Inspect the build <ArrowUpRight size={15} aria-hidden="true" /></ProjectLink>}
                </div>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className={styles.processSection}>
        <div className={s.wrapWide}>
          <div className={styles.processHeading} data-reveal><span className={s.kicker}>How I work</span><h2 className={styles.sectionTitle}>From healthcare problem to working system.</h2><p>AI is the build partner. Domain judgment, privacy boundaries, and testing decide whether the result is useful.</p></div>
          <div className={styles.processGrid}>
            {process.map((step, index) => (
              <article key={step[0]} className={styles.processStep} data-reveal>
                <div className={styles.processTop}><span>{step[0]}</span>{index < process.length - 1 && <span className={styles.processConnector} aria-hidden="true" />}</div>
                <h3>{step[1]}</h3><p>{step[2]}</p>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className={styles.teachingSection}>
        <div className={s.wrapWide}>
          <div className={styles.sectionIntro} data-reveal>
            <div><span className={s.kickerGold}>Learn from the build</span><h2 className={styles.sectionTitle}>Technical enough to use. Clear enough to teach.</h2></div>
            <p>Every session connects the tool to a real workflow, a risk boundary, and an outcome your audience understands.</p>
          </div>
          <div className={styles.teachingGrid}>
            {teaching.map(item => (
              <article key={item[0]} className={styles.teachingCard} data-reveal><Sparkles size={18} aria-hidden="true" /><span>{item[0]}</span><h3>{item[1]}</h3><p>{item[2]}</p><CheckCircle2 size={18} aria-hidden="true" className={styles.teachingCheck} /></article>
            ))}
          </div>
          <div className={styles.teachingAction}><Link to={WORKSHOPS_PATH} className={`${s.btnGold} ${s.btnLg}`}>See workshop formats and pricing <ArrowUpRight size={17} aria-hidden="true" /></Link></div>
        </div>
      </section>

      <section className={styles.writingSection}>
        <div className={s.wrapWide}>
          <div className={styles.writingHeader} data-reveal>
            <div><span className={s.kicker}>The Healthcare AI Build Library</span><h2 className={styles.sectionTitle}>What I am testing and teaching now.</h2></div>
            <Link to="/blog" className={s.btnGhost}>Read every build note <ArrowUpRight size={15} aria-hidden="true" /></Link>
          </div>
          <div className={styles.writingGrid}>
            {featuredPosts.map((post, index) => (
              <Link key={post.slug} to={`/blog/${post.slug}`} className={styles.articleCard} data-reveal>
                <span className={styles.articleNumber}>{String(index + 1).padStart(2, '0')}</span><span className={styles.articleMeta}>{post.category} · {post.date}</span>
                <h3>{post.title}</h3><p>{post.excerpt}</p><span className={styles.articleLink}>Read the build note <ArrowUpRight size={14} aria-hidden="true" /></span>
              </Link>
            ))}
          </div>
        </div>
      </section>

      <section className={styles.faqSection} id="faq">
        <div className={s.wrapWide}>
          <div className={styles.sectionIntro} data-reveal>
            <div><span className={s.kickerGold}>Common questions</span><h2 className={styles.sectionTitle}>What people ask before they book.</h2></div>
            <p>Short, direct answers. If yours is not here, email hello@icanteachyouai.com and it gets answered by a person.</p>
          </div>
          <div className={styles.faqList}>
            {HOME_FAQ.map((item, i) => (
              <details key={item.q} className={styles.faqItem} data-reveal style={{ ['--reveal-delay' as string]: `${i * 50}ms` }}>
                <summary><h3>{item.q}</h3></summary>
                <p>{item.a}</p>
              </details>
            ))}
          </div>
        </div>
      </section>

      <section className={styles.finalSection}>
        <div className={`${s.wrapWide} ${styles.finalGrid}`} data-reveal>
          <div><span className={s.kickerGold}>Bring practical AI to your team</span><h2>Stop explaining what AI is. Start showing what it can do.</h2></div>
          <div className={styles.finalCopy}><p>Book a hands-on workshop, a build session, or a focused conversation about a healthcare workflow.</p><div className={styles.finalActions}><Link to={WORKSHOPS_PATH} className={`${s.btnGold} ${s.btnLg}`}>Book a workshop</Link><Link to="/services" className={`${s.btnOutline} ${s.btnLg}`}>See all services</Link></div></div>
        </div>
      </section>
    </div>
  );
}
